- site/src/components/sdkLanguages.js
- site/src/css/skds.module.css
- site/src/pages/sdks/csharp.tsx
- site/src/pages/sdks/java.tsx
- site/src/pages/sdks/node.tsx
- site/src/pages/sdks/php.tsx
- site/src/pages/sdks/python.tsx
- site/src/pages/sdks/ruby.tsx
> Isolate CSS for sdk product tables

- site/docs/webrtc/webhooks.md
- site/sidebar.js
small changes to description that I left out of the last PR 'cause I was too hasty.  Sorry for the spam - hopefully I'm learning
> edge 1018 - improve some descriptions

- site/specs-source/phoneNumberLookup.json
- site/src/pages/changelog.md
> Revert Phone Number Lookup spec from 1.0.6 to 1.0.5

- site/src/components/ApiReference.js
- site/src/css/custom.css
- site/src/pages/apis/dash-notifications.tsx
- site/src/pages/apis/dash.tsx
- site/src/pages/apis/messaging-international.tsx
- site/src/pages/apis/messaging.tsx
- site/src/pages/apis/multifactorauth.tsx
- site/src/pages/apis/number-lookup.tsx
- site/src/pages/apis/voice.tsx
- site/src/pages/apis/webrtc.tsx
> DX-2167 Reactify API Reference Pages

- package-lock.json
- package.json
- site/docusaurus.config.js
Also cleaned up docusaurus config file (spacing)
> DX-2151 Clean up root Package.json file

- site/docs/messaging/createMessage.mdx
- site/docs/messaging/getMessage.mdx
- site/docs/messaging/mediaManagement.mdx
> DX-2155 Update Messaging Guides & Tutorials

- site/docusaurus.config.js
> DX-2137 Add Google Analytics Tag

- README.md
- site/templates/apiReference.tsx
> DX-2167-2 Update API Ref Page Template

- site/docs/voice/bxml/bridge.mdx
- site/docs/voice/bxml/conference.mdx
- site/docs/voice/bxml/forward.mdx
- site/docs/voice/bxml/gather.mdx
- site/docs/voice/bxml/hangup.mdx
- site/docs/voice/bxml/pause.mdx
- site/docs/voice/bxml/pauseRecording.mdx
- site/docs/voice/bxml/playAudio.mdx
- site/docs/voice/bxml/record.mdx
- site/docs/voice/bxml/redirect.mdx
- site/docs/voice/bxml/resumeRecording.mdx
- site/docs/voice/bxml/ring.mdx
- site/docs/voice/bxml/sendDtmf.mdx
- site/docs/voice/bxml/speakSentence.mdx
- site/docs/voice/bxml/startGather.mdx
- site/docs/voice/bxml/startRecording.mdx
- site/docs/voice/bxml/stopGather.mdx
- site/docs/voice/bxml/stopRecording.mdx
- site/docs/voice/bxml/tag.mdx
- site/docs/voice/bxml/transfer.mdx
> DX-2180 Update Node BXML examples

- site/specs-source/voice.json
- site/src/pages/changelog.md
> DX-2199 Add AMD to Voice API spec

- site/specs-source/voice.json
Update Tags, Summaries, and Descriptions of each endpoint to better display the reference on the docsite
> DX-2192 Update Voice API Spec

- site/docusaurus.config.js
- site/specs-docs-only/messagingInternational.json
- site/src/pages/changelog.md
> DX-2207 Update Messaging International Spec

- site/scripts/add-code-snippets-oas.js
- site/src/css/custom.css
> Dx 2171 Same Width Code Snippet Buttons

- site/docs/account/networkBridge.mdx
> Update and rename networkBridge.md to networkBridge.mdx

- site/specs-source/voice.json
- site/src/pages/changelog.md
> DX-2220 Parity with Voice API Spec Copy

- site/docs/voice/webhooks/machineDetectionComplete.mdx
- site/src/pages/changelog.md
> VAPI-932 Update AMD docs to better reflect async flow

- site/docs/voice/bxml/ring.mdx
> DX-2287 Updated Ring BXML code snippets

- site/docs/voice/about.mdx
- site/src/pages/changelog.md
> VAPI-772 Add more information to the About page

- site/specs-docs-only/dash.json
- site/specs-docs-only/dashNotifications.json
- site/specs-docs-only/messagingInternational.json
- site/specs-source/messaging.json
- site/specs-source/multiFactorAuth.json
- site/specs-source/phoneNumberLookup.json
- site/specs-source/voice.json
- site/specs-source/webRtc.json
> DX-2298 add Base Path to OpenAPI Descriptions

- site/docs/account/structure.md
> Remove note about sub-account max

- site/docs/account/applications.mdx
- site/docs/voice/quickStart.mdx
- site/src/pages/changelog.md
> VAPI-922 Update callback docs to be more specific

- site/sidebar.js
> DX-2313 Add API Reference to Docs Sidebar

- site/specs-docs-only/dash.json
> DX-2308 Add Tags to DASH API Spec

- package.json
- sdk-generation/config/masterConfig.json
> DX-2329 Remove APIMatic from SDK Deployment Logic

- .github/workflows/spec-validate.yaml
- site/specs-source/messaging.json
> DX-2330 Replace APIMatic with Stoplight

- site/docs/webrtc/overview.md
- site/docs/webrtc/quickstart.md
> DX-2321 Fix Links for Cutover

- site/docusaurus.config.js
> DX-2161 Update Algolia API Key

- site/docs/messaging/campaign-management/csp/campaign-ui.mdx
- site/docs/messaging/campaign-management/imports/imports-ui.mdx
- site/src/pages/changelog.md
- site/static/csv/tn_option_order_sample.csv
> BWDB-11411 added downloadable CSV sample for Bulk TN Option Order

- site/docs/numbers/csrLookupTool.mdx
- site/docs/numbers/hostingNumbers.mdx
- site/sidebar.js
> Migrate CSR Guide

- site/src/css/custom.css
> DX-2443 Shrink Font Size

- .github/workflows/publish-docsite.yml
**⚠️Please do not make any changes to spec files in this repository!⚠️**
**All spec changes should be done in the [api-specs](https://github.com/Bandwidth/api-specs) repository.**
**Please follow the [Guide](https://bandwidth-jira.atlassian.net/wiki/spaces/DX/pages/4098359409/How+to+Update+API+Specifications+and+Contribute+to+Developer+Documentation) for contributing to our developer documentation.**
> SWI-2266 Add env vars to cypress
